name: Build Documentation

on:
  push:
  workflow_run:
    types:
      - completed
    workflows:
      - Update SDK
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Preprocess the SDK files
        run: python preprocessor.py

#       - name: Generate API reference
#         uses: mattnotmitt/doxygen-action@1.9.4
#         with:
#           doxyfile-path: ./Doxyfile_api
#           additional-packages: graphviz

      - name: Generate the English documentation
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          doxyfile-path: ./Doxyfile_en
          additional-packages: graphviz

      - name: Translate the documentation
        uses: crowdin/github-action@1.4.12
        with:
          upload_sources: true
          download_translations: true
          push_translations: false
          create_pull_request: false
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          source: 'docs/en/**/*'
          translation: 'docs/%two_letters_code%/**/%original_file_name%'
          base_url: 'https://api.crowdin.com'
          base_path: '.'
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          
      - name: Upload the pages artifact
        uses: actions/upload-pages-artifact@v1.0.3
        with:
          path: docs/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the pages
        id: deployment
        uses: actions/deploy-pages@v1.0.10
