name: Build Documentation

on:
  push:
  workflow_run:
    types:
      - completed
    workflows:
      - Update SDK
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Preprocess the SDK files
        run: python preprocessor.py

      - name: Generate API reference
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          doxyfile-path: ./Doxyfile_api
          additional-packages: graphviz

      - name: Generate English documentation
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          doxyfile-path: ./Doxyfile_en
          additional-packages: graphviz

      - name: Generate Chinese documentation
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          doxyfile-path: ./Doxyfile_zh-Hans
          additional-packages: graphviz

      - name: Upload the pages artifact
        uses: actions/upload-pages-artifact@v1.0.3
        with:
          path: docs/
          
      - name: Upload the artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: docs/en/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the pages
        id: deployment
        uses: actions/deploy-pages@v1.0.10
