name: Build Documentation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Preprocess the SDK files
        run: python preprocessor.py

      - name: Generate English documentation
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          doxyfile-path: ./Doxyfile_en
          additional-packages: graphviz

      - name: Generate Chinese documentation
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          doxyfile-path: ./Doxyfile_zh-Hans
          additional-packages: graphviz

      - name: Generate API reference
        uses: mattnotmitt/doxygen-action@1.9.4
        with:
          doxyfile-path: ./Doxyfile_api
          additional-packages: graphviz

      - name: Upload the artifact
        uses: actions/upload-pages-artifact@v1.0.3
        with:
          path: docs/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the pages
        id: deployment
        uses: actions/deploy-pages@v1.0.10
