name: Build Documentation

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          
      - uses: mattnotmitt/doxygen-action@1.9.4
        with:
          doxyfile-path: ./Doxyfile_en
          additional-packages: graphviz
          
      - uses: mattnotmitt/doxygen-action@1.9.4
        with:
          doxyfile-path: ./Doxyfile_zh-Hans
          additional-packages: graphviz
          
      - uses: mattnotmitt/doxygen-action@1.9.4
        with:
          doxyfile-path: ./Doxyfile_raw
          additional-packages: graphviz

      - uses: actions/upload-pages-artifact@v1.0.3
        with:
          path: docs/
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1.0.10
